# Generated by Django 4.0.4 on 2022-05-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='description_2',
            field=models.TextField(max_length=300),
        ),
    ]
