# Generated by Django 4.0.4 on 2022-05-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_evento_description_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='description_2',
            field=models.TextField(),
        ),
    ]
