# Generated by Django 4.0.4 on 2022-06-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_evento_description_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vivo', models.CharField(max_length=200)),
                ('frame', models.CharField(max_length=1000)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
