# Generated by Django 4.0.4 on 2022-06-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_vivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivo',
            name='frame',
            field=models.URLField(max_length=1000),
        ),
    ]
