# Generated by Django 4.0.4 on 2022-06-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_vivo_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominicales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dom', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('evento_image', models.ImageField(upload_to='photos/fotos')),
                ('pdf', models.FileField(upload_to='pdf/pdfs')),
                ('audio', models.FileField(upload_to='audio/audios')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
