# Generated by Django 4.0.4 on 2022-06-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_dominicales'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominicales',
            name='dia',
            field=models.CharField(choices=[('0', 'Domingos'), ('1', 'Jueves'), ('2', 'Martes')], default='Domingo', max_length=1),
        ),
    ]
