# Generated by Django 4.0.4 on 2022-07-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_avisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemasDom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tema', models.CharField(max_length=60, verbose_name='Tema')),
                ('fecha', models.DateField(verbose_name='Fecha:')),
                ('pdf', models.FileField(upload_to='pdf/pdfs', verbose_name='Pdf:')),
                ('is_available', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='avisos',
            options={'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='dominicales',
            options={'verbose_name': 'Dominical', 'verbose_name_plural': 'Dominicales'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterModelOptions(
            name='vivo',
            options={'verbose_name': 'En vivo', 'verbose_name_plural': 'En vivos'},
        ),
        migrations.AlterField(
            model_name='avisos',
            name='aviso_image',
            field=models.ImageField(upload_to='photos/fotos', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='avisos',
            name='aviso_name',
            field=models.CharField(max_length=50, verbose_name='Nombre del Aviso:'),
        ),
        migrations.AlterField(
            model_name='avisos',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Caategoria:'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción:'),
        ),
        migrations.AlterField(
            model_name='dominicales',
            name='audio',
            field=models.FileField(upload_to='audio/audios', verbose_name='Audio:'),
        ),
        migrations.AlterField(
            model_name='dominicales',
            name='dia',
            field=models.CharField(choices=[('Domingos', 'Domingos'), ('Jueves', 'Jueves'), ('Martes', 'Martes')], default='Domingo', max_length=50, verbose_name='Dia:'),
        ),
        migrations.AlterField(
            model_name='dominicales',
            name='evento_image',
            field=models.ImageField(upload_to='photos/fotos', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='dominicales',
            name='fecha',
            field=models.DateField(verbose_name='Fecha:'),
        ),
        migrations.AlterField(
            model_name='dominicales',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='dominicales',
            name='name_dom',
            field=models.CharField(max_length=100, verbose_name='Título Dominical:'),
        ),
        migrations.AlterField(
            model_name='dominicales',
            name='pdf',
            field=models.FileField(upload_to='pdf/pdfs', verbose_name='Pdf:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='description_1',
            field=models.CharField(max_length=100, verbose_name='Descripción 1:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='description_2',
            field=models.TextField(verbose_name='Descripción 2:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='evento_image',
            field=models.ImageField(upload_to='photos/fotos', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='evento_name',
            field=models.CharField(max_length=50, verbose_name='Nombre del Evento:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateField(verbose_name='Fecha del Evento:'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/fotos', verbose_name='Imagen:'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre de la Imagen:'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='vivo',
            name='frame',
            field=models.URLField(verbose_name='URL:'),
        ),
        migrations.AlterField(
            model_name='vivo',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
        migrations.AlterField(
            model_name='vivo',
            name='name_vivo',
            field=models.CharField(max_length=200, verbose_name='Nombre:'),
        ),
    ]
